/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiIngestionRunEventsRouteImport } from './routes/api/ingestion-run-events'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as AuthedVulnerabilitiesIndexRouteImport } from './routes/_authed/vulnerabilities/index'
import { Route as AuthedSoftwareIndexRouteImport } from './routes/_authed/software/index'
import { Route as AuthedRemediationIndexRouteImport } from './routes/_authed/remediation/index'
import { Route as AuthedDevicesIndexRouteImport } from './routes/_authed/devices/index'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedAuditLogIndexRouteImport } from './routes/_authed/audit-log/index'
import { Route as AuthedAssetsIndexRouteImport } from './routes/_authed/assets/index'
import { Route as AuthedApprovalsIndexRouteImport } from './routes/_authed/approvals/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedActionsIndexRouteImport } from './routes/_authed/actions/index'
import { Route as ApiInternalEventsRouteImport } from './routes/api/internal/events'
import { Route as AuthedVulnerabilitiesChangesRouteImport } from './routes/_authed/vulnerabilities/changes'
import { Route as AuthedVulnerabilitiesIdRouteImport } from './routes/_authed/vulnerabilities/$id'
import { Route as AuthedSoftwareIdRouteImport } from './routes/_authed/software/$id'
import { Route as AuthedRemediationTasksRouteImport } from './routes/_authed/remediation/tasks'
import { Route as AuthedDashboardTechnicalRouteImport } from './routes/_authed/dashboard/technical'
import { Route as AuthedDashboardSecurityRouteImport } from './routes/_authed/dashboard/security'
import { Route as AuthedDashboardMyAssetsRouteImport } from './routes/_authed/dashboard/my-assets'
import { Route as AuthedDashboardExecutiveRouteImport } from './routes/_authed/dashboard/executive'
import { Route as AuthedAssetsIdRouteImport } from './routes/_authed/assets/$id'
import { Route as AuthedApprovalsIdRouteImport } from './routes/_authed/approvals/$id'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminSourcesRouteImport } from './routes/_authed/admin/sources'
import { Route as AuthedAdminSecurityProfilesRouteImport } from './routes/_authed/admin/security-profiles'
import { Route as AuthedAdminMaintenanceRouteImport } from './routes/_authed/admin/maintenance'
import { Route as AuthedAdminBusinessLabelsRouteImport } from './routes/_authed/admin/business-labels'
import { Route as AuthedAdminAdvancedToolsRouteImport } from './routes/_authed/admin/advanced-tools'
import { Route as AuthedAdminWorkflowsIndexRouteImport } from './routes/_authed/admin/workflows/index'
import { Route as AuthedAdminTenantsIndexRouteImport } from './routes/_authed/admin/tenants/index'
import { Route as AuthedAdminTeamsIndexRouteImport } from './routes/_authed/admin/teams/index'
import { Route as AuthedAdminIntegrationsIndexRouteImport } from './routes/_authed/admin/integrations/index'
import { Route as AuthedAdminAssetRulesIndexRouteImport } from './routes/_authed/admin/asset-rules/index'
import { Route as AuthedSoftwareIdRemediationRouteImport } from './routes/_authed/software/$id_.remediation'
import { Route as AuthedRemediationTaskIdRouteImport } from './routes/_authed/remediation/task.$id'
import { Route as AuthedDashboardMyAssetsAttentionRouteImport } from './routes/_authed/dashboard/my-assets.attention'
import { Route as AuthedAssetsIdRemediationRouteImport } from './routes/_authed/assets/$id_.remediation'
import { Route as AuthedAdminWorkflowsNewRouteImport } from './routes/_authed/admin/workflows/new'
import { Route as AuthedAdminWorkflowsIdRouteImport } from './routes/_authed/admin/workflows/$id'
import { Route as AuthedAdminTenantsIdRouteImport } from './routes/_authed/admin/tenants/$id'
import { Route as AuthedAdminTeamsIdRouteImport } from './routes/_authed/admin/teams/$id'
import { Route as AuthedAdminPlatformNotificationsRouteImport } from './routes/_authed/admin/platform/notifications'
import { Route as AuthedAdminPlatformAiRouteImport } from './routes/_authed/admin/platform/ai'
import { Route as AuthedAdminAssetRulesNewRouteImport } from './routes/_authed/admin/asset-rules/new'
import { Route as AuthedAdminAssetRulesIdRouteImport } from './routes/_authed/admin/asset-rules/$id'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestionRunEventsRoute = ApiIngestionRunEventsRouteImport.update({
  id: '/api/ingestion-run-events',
  path: '/api/ingestion-run-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedVulnerabilitiesIndexRoute =
  AuthedVulnerabilitiesIndexRouteImport.update({
    id: '/vulnerabilities/',
    path: '/vulnerabilities/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSoftwareIndexRoute = AuthedSoftwareIndexRouteImport.update({
  id: '/software/',
  path: '/software/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRemediationIndexRoute = AuthedRemediationIndexRouteImport.update({
  id: '/remediation/',
  path: '/remediation/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevicesIndexRoute = AuthedDevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditLogIndexRoute = AuthedAuditLogIndexRouteImport.update({
  id: '/audit-log/',
  path: '/audit-log/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAssetsIndexRoute = AuthedAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApprovalsIndexRoute = AuthedApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActionsIndexRoute = AuthedActionsIndexRouteImport.update({
  id: '/actions/',
  path: '/actions/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiInternalEventsRoute = ApiInternalEventsRouteImport.update({
  id: '/api/internal/events',
  path: '/api/internal/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedVulnerabilitiesChangesRoute =
  AuthedVulnerabilitiesChangesRouteImport.update({
    id: '/vulnerabilities/changes',
    path: '/vulnerabilities/changes',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedVulnerabilitiesIdRoute = AuthedVulnerabilitiesIdRouteImport.update({
  id: '/vulnerabilities/$id',
  path: '/vulnerabilities/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSoftwareIdRoute = AuthedSoftwareIdRouteImport.update({
  id: '/software/$id',
  path: '/software/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRemediationTasksRoute = AuthedRemediationTasksRouteImport.update({
  id: '/remediation/tasks',
  path: '/remediation/tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardTechnicalRoute =
  AuthedDashboardTechnicalRouteImport.update({
    id: '/dashboard/technical',
    path: '/dashboard/technical',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardSecurityRoute = AuthedDashboardSecurityRouteImport.update({
  id: '/dashboard/security',
  path: '/dashboard/security',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardMyAssetsRoute = AuthedDashboardMyAssetsRouteImport.update({
  id: '/dashboard/my-assets',
  path: '/dashboard/my-assets',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardExecutiveRoute =
  AuthedDashboardExecutiveRouteImport.update({
    id: '/dashboard/executive',
    path: '/dashboard/executive',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAssetsIdRoute = AuthedAssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApprovalsIdRoute = AuthedApprovalsIdRouteImport.update({
  id: '/approvals/$id',
  path: '/approvals/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminSourcesRoute = AuthedAdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminSecurityProfilesRoute =
  AuthedAdminSecurityProfilesRouteImport.update({
    id: '/admin/security-profiles',
    path: '/admin/security-profiles',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMaintenanceRoute = AuthedAdminMaintenanceRouteImport.update({
  id: '/admin/maintenance',
  path: '/admin/maintenance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminBusinessLabelsRoute =
  AuthedAdminBusinessLabelsRouteImport.update({
    id: '/admin/business-labels',
    path: '/admin/business-labels',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminAdvancedToolsRoute =
  AuthedAdminAdvancedToolsRouteImport.update({
    id: '/admin/advanced-tools',
    path: '/admin/advanced-tools',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminWorkflowsIndexRoute =
  AuthedAdminWorkflowsIndexRouteImport.update({
    id: '/admin/workflows/',
    path: '/admin/workflows/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminTenantsIndexRoute = AuthedAdminTenantsIndexRouteImport.update({
  id: '/admin/tenants/',
  path: '/admin/tenants/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminTeamsIndexRoute = AuthedAdminTeamsIndexRouteImport.update({
  id: '/admin/teams/',
  path: '/admin/teams/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIntegrationsIndexRoute =
  AuthedAdminIntegrationsIndexRouteImport.update({
    id: '/admin/integrations/',
    path: '/admin/integrations/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminAssetRulesIndexRoute =
  AuthedAdminAssetRulesIndexRouteImport.update({
    id: '/admin/asset-rules/',
    path: '/admin/asset-rules/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSoftwareIdRemediationRoute =
  AuthedSoftwareIdRemediationRouteImport.update({
    id: '/software/$id_/remediation',
    path: '/software/$id/remediation',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedRemediationTaskIdRoute = AuthedRemediationTaskIdRouteImport.update({
  id: '/remediation/task/$id',
  path: '/remediation/task/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardMyAssetsAttentionRoute =
  AuthedDashboardMyAssetsAttentionRouteImport.update({
    id: '/attention',
    path: '/attention',
    getParentRoute: () => AuthedDashboardMyAssetsRoute,
  } as any)
const AuthedAssetsIdRemediationRoute =
  AuthedAssetsIdRemediationRouteImport.update({
    id: '/assets/$id_/remediation',
    path: '/assets/$id/remediation',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminWorkflowsNewRoute = AuthedAdminWorkflowsNewRouteImport.update({
  id: '/admin/workflows/new',
  path: '/admin/workflows/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminWorkflowsIdRoute = AuthedAdminWorkflowsIdRouteImport.update({
  id: '/admin/workflows/$id',
  path: '/admin/workflows/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminTenantsIdRoute = AuthedAdminTenantsIdRouteImport.update({
  id: '/admin/tenants/$id',
  path: '/admin/tenants/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminTeamsIdRoute = AuthedAdminTeamsIdRouteImport.update({
  id: '/admin/teams/$id',
  path: '/admin/teams/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminPlatformNotificationsRoute =
  AuthedAdminPlatformNotificationsRouteImport.update({
    id: '/admin/platform/notifications',
    path: '/admin/platform/notifications',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminPlatformAiRoute = AuthedAdminPlatformAiRouteImport.update({
  id: '/admin/platform/ai',
  path: '/admin/platform/ai',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminAssetRulesNewRoute =
  AuthedAdminAssetRulesNewRouteImport.update({
    id: '/admin/asset-rules/new',
    path: '/admin/asset-rules/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminAssetRulesIdRoute = AuthedAdminAssetRulesIdRouteImport.update({
  id: '/admin/asset-rules/$id',
  path: '/admin/asset-rules/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/api/ingestion-run-events': typeof ApiIngestionRunEventsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/setup/': typeof SetupIndexRoute
  '/admin/advanced-tools': typeof AuthedAdminAdvancedToolsRoute
  '/admin/business-labels': typeof AuthedAdminBusinessLabelsRoute
  '/admin/maintenance': typeof AuthedAdminMaintenanceRoute
  '/admin/security-profiles': typeof AuthedAdminSecurityProfilesRoute
  '/admin/sources': typeof AuthedAdminSourcesRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/approvals/$id': typeof AuthedApprovalsIdRoute
  '/assets/$id': typeof AuthedAssetsIdRoute
  '/dashboard/executive': typeof AuthedDashboardExecutiveRoute
  '/dashboard/my-assets': typeof AuthedDashboardMyAssetsRouteWithChildren
  '/dashboard/security': typeof AuthedDashboardSecurityRoute
  '/dashboard/technical': typeof AuthedDashboardTechnicalRoute
  '/remediation/tasks': typeof AuthedRemediationTasksRoute
  '/software/$id': typeof AuthedSoftwareIdRoute
  '/vulnerabilities/$id': typeof AuthedVulnerabilitiesIdRoute
  '/vulnerabilities/changes': typeof AuthedVulnerabilitiesChangesRoute
  '/api/internal/events': typeof ApiInternalEventsRoute
  '/actions/': typeof AuthedActionsIndexRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/approvals/': typeof AuthedApprovalsIndexRoute
  '/assets/': typeof AuthedAssetsIndexRoute
  '/audit-log/': typeof AuthedAuditLogIndexRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/devices/': typeof AuthedDevicesIndexRoute
  '/remediation/': typeof AuthedRemediationIndexRoute
  '/software/': typeof AuthedSoftwareIndexRoute
  '/vulnerabilities/': typeof AuthedVulnerabilitiesIndexRoute
  '/admin/asset-rules/$id': typeof AuthedAdminAssetRulesIdRoute
  '/admin/asset-rules/new': typeof AuthedAdminAssetRulesNewRoute
  '/admin/platform/ai': typeof AuthedAdminPlatformAiRoute
  '/admin/platform/notifications': typeof AuthedAdminPlatformNotificationsRoute
  '/admin/teams/$id': typeof AuthedAdminTeamsIdRoute
  '/admin/tenants/$id': typeof AuthedAdminTenantsIdRoute
  '/admin/workflows/$id': typeof AuthedAdminWorkflowsIdRoute
  '/admin/workflows/new': typeof AuthedAdminWorkflowsNewRoute
  '/assets/$id/remediation': typeof AuthedAssetsIdRemediationRoute
  '/dashboard/my-assets/attention': typeof AuthedDashboardMyAssetsAttentionRoute
  '/remediation/task/$id': typeof AuthedRemediationTaskIdRoute
  '/software/$id/remediation': typeof AuthedSoftwareIdRemediationRoute
  '/admin/asset-rules/': typeof AuthedAdminAssetRulesIndexRoute
  '/admin/integrations/': typeof AuthedAdminIntegrationsIndexRoute
  '/admin/teams/': typeof AuthedAdminTeamsIndexRoute
  '/admin/tenants/': typeof AuthedAdminTenantsIndexRoute
  '/admin/workflows/': typeof AuthedAdminWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/api/ingestion-run-events': typeof ApiIngestionRunEventsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/setup': typeof SetupIndexRoute
  '/admin/advanced-tools': typeof AuthedAdminAdvancedToolsRoute
  '/admin/business-labels': typeof AuthedAdminBusinessLabelsRoute
  '/admin/maintenance': typeof AuthedAdminMaintenanceRoute
  '/admin/security-profiles': typeof AuthedAdminSecurityProfilesRoute
  '/admin/sources': typeof AuthedAdminSourcesRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/approvals/$id': typeof AuthedApprovalsIdRoute
  '/assets/$id': typeof AuthedAssetsIdRoute
  '/dashboard/executive': typeof AuthedDashboardExecutiveRoute
  '/dashboard/my-assets': typeof AuthedDashboardMyAssetsRouteWithChildren
  '/dashboard/security': typeof AuthedDashboardSecurityRoute
  '/dashboard/technical': typeof AuthedDashboardTechnicalRoute
  '/remediation/tasks': typeof AuthedRemediationTasksRoute
  '/software/$id': typeof AuthedSoftwareIdRoute
  '/vulnerabilities/$id': typeof AuthedVulnerabilitiesIdRoute
  '/vulnerabilities/changes': typeof AuthedVulnerabilitiesChangesRoute
  '/api/internal/events': typeof ApiInternalEventsRoute
  '/actions': typeof AuthedActionsIndexRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/approvals': typeof AuthedApprovalsIndexRoute
  '/assets': typeof AuthedAssetsIndexRoute
  '/audit-log': typeof AuthedAuditLogIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/devices': typeof AuthedDevicesIndexRoute
  '/remediation': typeof AuthedRemediationIndexRoute
  '/software': typeof AuthedSoftwareIndexRoute
  '/vulnerabilities': typeof AuthedVulnerabilitiesIndexRoute
  '/admin/asset-rules/$id': typeof AuthedAdminAssetRulesIdRoute
  '/admin/asset-rules/new': typeof AuthedAdminAssetRulesNewRoute
  '/admin/platform/ai': typeof AuthedAdminPlatformAiRoute
  '/admin/platform/notifications': typeof AuthedAdminPlatformNotificationsRoute
  '/admin/teams/$id': typeof AuthedAdminTeamsIdRoute
  '/admin/tenants/$id': typeof AuthedAdminTenantsIdRoute
  '/admin/workflows/$id': typeof AuthedAdminWorkflowsIdRoute
  '/admin/workflows/new': typeof AuthedAdminWorkflowsNewRoute
  '/assets/$id/remediation': typeof AuthedAssetsIdRemediationRoute
  '/dashboard/my-assets/attention': typeof AuthedDashboardMyAssetsAttentionRoute
  '/remediation/task/$id': typeof AuthedRemediationTaskIdRoute
  '/software/$id/remediation': typeof AuthedSoftwareIdRemediationRoute
  '/admin/asset-rules': typeof AuthedAdminAssetRulesIndexRoute
  '/admin/integrations': typeof AuthedAdminIntegrationsIndexRoute
  '/admin/teams': typeof AuthedAdminTeamsIndexRoute
  '/admin/tenants': typeof AuthedAdminTenantsIndexRoute
  '/admin/workflows': typeof AuthedAdminWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/api/events': typeof ApiEventsRoute
  '/api/ingestion-run-events': typeof ApiIngestionRunEventsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/setup/': typeof SetupIndexRoute
  '/_authed/admin/advanced-tools': typeof AuthedAdminAdvancedToolsRoute
  '/_authed/admin/business-labels': typeof AuthedAdminBusinessLabelsRoute
  '/_authed/admin/maintenance': typeof AuthedAdminMaintenanceRoute
  '/_authed/admin/security-profiles': typeof AuthedAdminSecurityProfilesRoute
  '/_authed/admin/sources': typeof AuthedAdminSourcesRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/approvals/$id': typeof AuthedApprovalsIdRoute
  '/_authed/assets/$id': typeof AuthedAssetsIdRoute
  '/_authed/dashboard/executive': typeof AuthedDashboardExecutiveRoute
  '/_authed/dashboard/my-assets': typeof AuthedDashboardMyAssetsRouteWithChildren
  '/_authed/dashboard/security': typeof AuthedDashboardSecurityRoute
  '/_authed/dashboard/technical': typeof AuthedDashboardTechnicalRoute
  '/_authed/remediation/tasks': typeof AuthedRemediationTasksRoute
  '/_authed/software/$id': typeof AuthedSoftwareIdRoute
  '/_authed/vulnerabilities/$id': typeof AuthedVulnerabilitiesIdRoute
  '/_authed/vulnerabilities/changes': typeof AuthedVulnerabilitiesChangesRoute
  '/api/internal/events': typeof ApiInternalEventsRoute
  '/_authed/actions/': typeof AuthedActionsIndexRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/approvals/': typeof AuthedApprovalsIndexRoute
  '/_authed/assets/': typeof AuthedAssetsIndexRoute
  '/_authed/audit-log/': typeof AuthedAuditLogIndexRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/devices/': typeof AuthedDevicesIndexRoute
  '/_authed/remediation/': typeof AuthedRemediationIndexRoute
  '/_authed/software/': typeof AuthedSoftwareIndexRoute
  '/_authed/vulnerabilities/': typeof AuthedVulnerabilitiesIndexRoute
  '/_authed/admin/asset-rules/$id': typeof AuthedAdminAssetRulesIdRoute
  '/_authed/admin/asset-rules/new': typeof AuthedAdminAssetRulesNewRoute
  '/_authed/admin/platform/ai': typeof AuthedAdminPlatformAiRoute
  '/_authed/admin/platform/notifications': typeof AuthedAdminPlatformNotificationsRoute
  '/_authed/admin/teams/$id': typeof AuthedAdminTeamsIdRoute
  '/_authed/admin/tenants/$id': typeof AuthedAdminTenantsIdRoute
  '/_authed/admin/workflows/$id': typeof AuthedAdminWorkflowsIdRoute
  '/_authed/admin/workflows/new': typeof AuthedAdminWorkflowsNewRoute
  '/_authed/assets/$id_/remediation': typeof AuthedAssetsIdRemediationRoute
  '/_authed/dashboard/my-assets/attention': typeof AuthedDashboardMyAssetsAttentionRoute
  '/_authed/remediation/task/$id': typeof AuthedRemediationTaskIdRoute
  '/_authed/software/$id_/remediation': typeof AuthedSoftwareIdRemediationRoute
  '/_authed/admin/asset-rules/': typeof AuthedAdminAssetRulesIndexRoute
  '/_authed/admin/integrations/': typeof AuthedAdminIntegrationsIndexRoute
  '/_authed/admin/teams/': typeof AuthedAdminTeamsIndexRoute
  '/_authed/admin/tenants/': typeof AuthedAdminTenantsIndexRoute
  '/_authed/admin/workflows/': typeof AuthedAdminWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/events'
    | '/api/ingestion-run-events'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/setup/'
    | '/admin/advanced-tools'
    | '/admin/business-labels'
    | '/admin/maintenance'
    | '/admin/security-profiles'
    | '/admin/sources'
    | '/admin/users'
    | '/approvals/$id'
    | '/assets/$id'
    | '/dashboard/executive'
    | '/dashboard/my-assets'
    | '/dashboard/security'
    | '/dashboard/technical'
    | '/remediation/tasks'
    | '/software/$id'
    | '/vulnerabilities/$id'
    | '/vulnerabilities/changes'
    | '/api/internal/events'
    | '/actions/'
    | '/admin/'
    | '/approvals/'
    | '/assets/'
    | '/audit-log/'
    | '/dashboard/'
    | '/devices/'
    | '/remediation/'
    | '/software/'
    | '/vulnerabilities/'
    | '/admin/asset-rules/$id'
    | '/admin/asset-rules/new'
    | '/admin/platform/ai'
    | '/admin/platform/notifications'
    | '/admin/teams/$id'
    | '/admin/tenants/$id'
    | '/admin/workflows/$id'
    | '/admin/workflows/new'
    | '/assets/$id/remediation'
    | '/dashboard/my-assets/attention'
    | '/remediation/task/$id'
    | '/software/$id/remediation'
    | '/admin/asset-rules/'
    | '/admin/integrations/'
    | '/admin/teams/'
    | '/admin/tenants/'
    | '/admin/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/events'
    | '/api/ingestion-run-events'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/setup'
    | '/admin/advanced-tools'
    | '/admin/business-labels'
    | '/admin/maintenance'
    | '/admin/security-profiles'
    | '/admin/sources'
    | '/admin/users'
    | '/approvals/$id'
    | '/assets/$id'
    | '/dashboard/executive'
    | '/dashboard/my-assets'
    | '/dashboard/security'
    | '/dashboard/technical'
    | '/remediation/tasks'
    | '/software/$id'
    | '/vulnerabilities/$id'
    | '/vulnerabilities/changes'
    | '/api/internal/events'
    | '/actions'
    | '/admin'
    | '/approvals'
    | '/assets'
    | '/audit-log'
    | '/dashboard'
    | '/devices'
    | '/remediation'
    | '/software'
    | '/vulnerabilities'
    | '/admin/asset-rules/$id'
    | '/admin/asset-rules/new'
    | '/admin/platform/ai'
    | '/admin/platform/notifications'
    | '/admin/teams/$id'
    | '/admin/tenants/$id'
    | '/admin/workflows/$id'
    | '/admin/workflows/new'
    | '/assets/$id/remediation'
    | '/dashboard/my-assets/attention'
    | '/remediation/task/$id'
    | '/software/$id/remediation'
    | '/admin/asset-rules'
    | '/admin/integrations'
    | '/admin/teams'
    | '/admin/tenants'
    | '/admin/workflows'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/api/events'
    | '/api/ingestion-run-events'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/setup/'
    | '/_authed/admin/advanced-tools'
    | '/_authed/admin/business-labels'
    | '/_authed/admin/maintenance'
    | '/_authed/admin/security-profiles'
    | '/_authed/admin/sources'
    | '/_authed/admin/users'
    | '/_authed/approvals/$id'
    | '/_authed/assets/$id'
    | '/_authed/dashboard/executive'
    | '/_authed/dashboard/my-assets'
    | '/_authed/dashboard/security'
    | '/_authed/dashboard/technical'
    | '/_authed/remediation/tasks'
    | '/_authed/software/$id'
    | '/_authed/vulnerabilities/$id'
    | '/_authed/vulnerabilities/changes'
    | '/api/internal/events'
    | '/_authed/actions/'
    | '/_authed/admin/'
    | '/_authed/approvals/'
    | '/_authed/assets/'
    | '/_authed/audit-log/'
    | '/_authed/dashboard/'
    | '/_authed/devices/'
    | '/_authed/remediation/'
    | '/_authed/software/'
    | '/_authed/vulnerabilities/'
    | '/_authed/admin/asset-rules/$id'
    | '/_authed/admin/asset-rules/new'
    | '/_authed/admin/platform/ai'
    | '/_authed/admin/platform/notifications'
    | '/_authed/admin/teams/$id'
    | '/_authed/admin/tenants/$id'
    | '/_authed/admin/workflows/$id'
    | '/_authed/admin/workflows/new'
    | '/_authed/assets/$id_/remediation'
    | '/_authed/dashboard/my-assets/attention'
    | '/_authed/remediation/task/$id'
    | '/_authed/software/$id_/remediation'
    | '/_authed/admin/asset-rules/'
    | '/_authed/admin/integrations/'
    | '/_authed/admin/teams/'
    | '/_authed/admin/tenants/'
    | '/_authed/admin/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiEventsRoute: typeof ApiEventsRoute
  ApiIngestionRunEventsRoute: typeof ApiIngestionRunEventsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  SetupIndexRoute: typeof SetupIndexRoute
  ApiInternalEventsRoute: typeof ApiInternalEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingestion-run-events': {
      id: '/api/ingestion-run-events'
      path: '/api/ingestion-run-events'
      fullPath: '/api/ingestion-run-events'
      preLoaderRoute: typeof ApiIngestionRunEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/vulnerabilities/': {
      id: '/_authed/vulnerabilities/'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities/'
      preLoaderRoute: typeof AuthedVulnerabilitiesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/software/': {
      id: '/_authed/software/'
      path: '/software'
      fullPath: '/software/'
      preLoaderRoute: typeof AuthedSoftwareIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/remediation/': {
      id: '/_authed/remediation/'
      path: '/remediation'
      fullPath: '/remediation/'
      preLoaderRoute: typeof AuthedRemediationIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/devices/': {
      id: '/_authed/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AuthedDevicesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit-log/': {
      id: '/_authed/audit-log/'
      path: '/audit-log'
      fullPath: '/audit-log/'
      preLoaderRoute: typeof AuthedAuditLogIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assets/': {
      id: '/_authed/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthedAssetsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/approvals/': {
      id: '/_authed/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AuthedApprovalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/actions/': {
      id: '/_authed/actions/'
      path: '/actions'
      fullPath: '/actions/'
      preLoaderRoute: typeof AuthedActionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/internal/events': {
      id: '/api/internal/events'
      path: '/api/internal/events'
      fullPath: '/api/internal/events'
      preLoaderRoute: typeof ApiInternalEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/vulnerabilities/changes': {
      id: '/_authed/vulnerabilities/changes'
      path: '/vulnerabilities/changes'
      fullPath: '/vulnerabilities/changes'
      preLoaderRoute: typeof AuthedVulnerabilitiesChangesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/vulnerabilities/$id': {
      id: '/_authed/vulnerabilities/$id'
      path: '/vulnerabilities/$id'
      fullPath: '/vulnerabilities/$id'
      preLoaderRoute: typeof AuthedVulnerabilitiesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/software/$id': {
      id: '/_authed/software/$id'
      path: '/software/$id'
      fullPath: '/software/$id'
      preLoaderRoute: typeof AuthedSoftwareIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/remediation/tasks': {
      id: '/_authed/remediation/tasks'
      path: '/remediation/tasks'
      fullPath: '/remediation/tasks'
      preLoaderRoute: typeof AuthedRemediationTasksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/technical': {
      id: '/_authed/dashboard/technical'
      path: '/dashboard/technical'
      fullPath: '/dashboard/technical'
      preLoaderRoute: typeof AuthedDashboardTechnicalRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/security': {
      id: '/_authed/dashboard/security'
      path: '/dashboard/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof AuthedDashboardSecurityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/my-assets': {
      id: '/_authed/dashboard/my-assets'
      path: '/dashboard/my-assets'
      fullPath: '/dashboard/my-assets'
      preLoaderRoute: typeof AuthedDashboardMyAssetsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/executive': {
      id: '/_authed/dashboard/executive'
      path: '/dashboard/executive'
      fullPath: '/dashboard/executive'
      preLoaderRoute: typeof AuthedDashboardExecutiveRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assets/$id': {
      id: '/_authed/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthedAssetsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/approvals/$id': {
      id: '/_authed/approvals/$id'
      path: '/approvals/$id'
      fullPath: '/approvals/$id'
      preLoaderRoute: typeof AuthedApprovalsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/sources': {
      id: '/_authed/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AuthedAdminSourcesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/security-profiles': {
      id: '/_authed/admin/security-profiles'
      path: '/admin/security-profiles'
      fullPath: '/admin/security-profiles'
      preLoaderRoute: typeof AuthedAdminSecurityProfilesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/maintenance': {
      id: '/_authed/admin/maintenance'
      path: '/admin/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AuthedAdminMaintenanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/business-labels': {
      id: '/_authed/admin/business-labels'
      path: '/admin/business-labels'
      fullPath: '/admin/business-labels'
      preLoaderRoute: typeof AuthedAdminBusinessLabelsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/advanced-tools': {
      id: '/_authed/admin/advanced-tools'
      path: '/admin/advanced-tools'
      fullPath: '/admin/advanced-tools'
      preLoaderRoute: typeof AuthedAdminAdvancedToolsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/workflows/': {
      id: '/_authed/admin/workflows/'
      path: '/admin/workflows'
      fullPath: '/admin/workflows/'
      preLoaderRoute: typeof AuthedAdminWorkflowsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/tenants/': {
      id: '/_authed/admin/tenants/'
      path: '/admin/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AuthedAdminTenantsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/teams/': {
      id: '/_authed/admin/teams/'
      path: '/admin/teams'
      fullPath: '/admin/teams/'
      preLoaderRoute: typeof AuthedAdminTeamsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/integrations/': {
      id: '/_authed/admin/integrations/'
      path: '/admin/integrations'
      fullPath: '/admin/integrations/'
      preLoaderRoute: typeof AuthedAdminIntegrationsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/asset-rules/': {
      id: '/_authed/admin/asset-rules/'
      path: '/admin/asset-rules'
      fullPath: '/admin/asset-rules/'
      preLoaderRoute: typeof AuthedAdminAssetRulesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/software/$id_/remediation': {
      id: '/_authed/software/$id_/remediation'
      path: '/software/$id/remediation'
      fullPath: '/software/$id/remediation'
      preLoaderRoute: typeof AuthedSoftwareIdRemediationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/remediation/task/$id': {
      id: '/_authed/remediation/task/$id'
      path: '/remediation/task/$id'
      fullPath: '/remediation/task/$id'
      preLoaderRoute: typeof AuthedRemediationTaskIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/my-assets/attention': {
      id: '/_authed/dashboard/my-assets/attention'
      path: '/attention'
      fullPath: '/dashboard/my-assets/attention'
      preLoaderRoute: typeof AuthedDashboardMyAssetsAttentionRouteImport
      parentRoute: typeof AuthedDashboardMyAssetsRoute
    }
    '/_authed/assets/$id_/remediation': {
      id: '/_authed/assets/$id_/remediation'
      path: '/assets/$id/remediation'
      fullPath: '/assets/$id/remediation'
      preLoaderRoute: typeof AuthedAssetsIdRemediationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/workflows/new': {
      id: '/_authed/admin/workflows/new'
      path: '/admin/workflows/new'
      fullPath: '/admin/workflows/new'
      preLoaderRoute: typeof AuthedAdminWorkflowsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/workflows/$id': {
      id: '/_authed/admin/workflows/$id'
      path: '/admin/workflows/$id'
      fullPath: '/admin/workflows/$id'
      preLoaderRoute: typeof AuthedAdminWorkflowsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/tenants/$id': {
      id: '/_authed/admin/tenants/$id'
      path: '/admin/tenants/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AuthedAdminTenantsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/teams/$id': {
      id: '/_authed/admin/teams/$id'
      path: '/admin/teams/$id'
      fullPath: '/admin/teams/$id'
      preLoaderRoute: typeof AuthedAdminTeamsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/platform/notifications': {
      id: '/_authed/admin/platform/notifications'
      path: '/admin/platform/notifications'
      fullPath: '/admin/platform/notifications'
      preLoaderRoute: typeof AuthedAdminPlatformNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/platform/ai': {
      id: '/_authed/admin/platform/ai'
      path: '/admin/platform/ai'
      fullPath: '/admin/platform/ai'
      preLoaderRoute: typeof AuthedAdminPlatformAiRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/asset-rules/new': {
      id: '/_authed/admin/asset-rules/new'
      path: '/admin/asset-rules/new'
      fullPath: '/admin/asset-rules/new'
      preLoaderRoute: typeof AuthedAdminAssetRulesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/asset-rules/$id': {
      id: '/_authed/admin/asset-rules/$id'
      path: '/admin/asset-rules/$id'
      fullPath: '/admin/asset-rules/$id'
      preLoaderRoute: typeof AuthedAdminAssetRulesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedDashboardMyAssetsRouteChildren {
  AuthedDashboardMyAssetsAttentionRoute: typeof AuthedDashboardMyAssetsAttentionRoute
}

const AuthedDashboardMyAssetsRouteChildren: AuthedDashboardMyAssetsRouteChildren =
  {
    AuthedDashboardMyAssetsAttentionRoute:
      AuthedDashboardMyAssetsAttentionRoute,
  }

const AuthedDashboardMyAssetsRouteWithChildren =
  AuthedDashboardMyAssetsRoute._addFileChildren(
    AuthedDashboardMyAssetsRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedAdminAdvancedToolsRoute: typeof AuthedAdminAdvancedToolsRoute
  AuthedAdminBusinessLabelsRoute: typeof AuthedAdminBusinessLabelsRoute
  AuthedAdminMaintenanceRoute: typeof AuthedAdminMaintenanceRoute
  AuthedAdminSecurityProfilesRoute: typeof AuthedAdminSecurityProfilesRoute
  AuthedAdminSourcesRoute: typeof AuthedAdminSourcesRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedApprovalsIdRoute: typeof AuthedApprovalsIdRoute
  AuthedAssetsIdRoute: typeof AuthedAssetsIdRoute
  AuthedDashboardExecutiveRoute: typeof AuthedDashboardExecutiveRoute
  AuthedDashboardMyAssetsRoute: typeof AuthedDashboardMyAssetsRouteWithChildren
  AuthedDashboardSecurityRoute: typeof AuthedDashboardSecurityRoute
  AuthedDashboardTechnicalRoute: typeof AuthedDashboardTechnicalRoute
  AuthedRemediationTasksRoute: typeof AuthedRemediationTasksRoute
  AuthedSoftwareIdRoute: typeof AuthedSoftwareIdRoute
  AuthedVulnerabilitiesIdRoute: typeof AuthedVulnerabilitiesIdRoute
  AuthedVulnerabilitiesChangesRoute: typeof AuthedVulnerabilitiesChangesRoute
  AuthedActionsIndexRoute: typeof AuthedActionsIndexRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedApprovalsIndexRoute: typeof AuthedApprovalsIndexRoute
  AuthedAssetsIndexRoute: typeof AuthedAssetsIndexRoute
  AuthedAuditLogIndexRoute: typeof AuthedAuditLogIndexRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDevicesIndexRoute: typeof AuthedDevicesIndexRoute
  AuthedRemediationIndexRoute: typeof AuthedRemediationIndexRoute
  AuthedSoftwareIndexRoute: typeof AuthedSoftwareIndexRoute
  AuthedVulnerabilitiesIndexRoute: typeof AuthedVulnerabilitiesIndexRoute
  AuthedAdminAssetRulesIdRoute: typeof AuthedAdminAssetRulesIdRoute
  AuthedAdminAssetRulesNewRoute: typeof AuthedAdminAssetRulesNewRoute
  AuthedAdminPlatformAiRoute: typeof AuthedAdminPlatformAiRoute
  AuthedAdminPlatformNotificationsRoute: typeof AuthedAdminPlatformNotificationsRoute
  AuthedAdminTeamsIdRoute: typeof AuthedAdminTeamsIdRoute
  AuthedAdminTenantsIdRoute: typeof AuthedAdminTenantsIdRoute
  AuthedAdminWorkflowsIdRoute: typeof AuthedAdminWorkflowsIdRoute
  AuthedAdminWorkflowsNewRoute: typeof AuthedAdminWorkflowsNewRoute
  AuthedAssetsIdRemediationRoute: typeof AuthedAssetsIdRemediationRoute
  AuthedRemediationTaskIdRoute: typeof AuthedRemediationTaskIdRoute
  AuthedSoftwareIdRemediationRoute: typeof AuthedSoftwareIdRemediationRoute
  AuthedAdminAssetRulesIndexRoute: typeof AuthedAdminAssetRulesIndexRoute
  AuthedAdminIntegrationsIndexRoute: typeof AuthedAdminIntegrationsIndexRoute
  AuthedAdminTeamsIndexRoute: typeof AuthedAdminTeamsIndexRoute
  AuthedAdminTenantsIndexRoute: typeof AuthedAdminTenantsIndexRoute
  AuthedAdminWorkflowsIndexRoute: typeof AuthedAdminWorkflowsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminAdvancedToolsRoute: AuthedAdminAdvancedToolsRoute,
  AuthedAdminBusinessLabelsRoute: AuthedAdminBusinessLabelsRoute,
  AuthedAdminMaintenanceRoute: AuthedAdminMaintenanceRoute,
  AuthedAdminSecurityProfilesRoute: AuthedAdminSecurityProfilesRoute,
  AuthedAdminSourcesRoute: AuthedAdminSourcesRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedApprovalsIdRoute: AuthedApprovalsIdRoute,
  AuthedAssetsIdRoute: AuthedAssetsIdRoute,
  AuthedDashboardExecutiveRoute: AuthedDashboardExecutiveRoute,
  AuthedDashboardMyAssetsRoute: AuthedDashboardMyAssetsRouteWithChildren,
  AuthedDashboardSecurityRoute: AuthedDashboardSecurityRoute,
  AuthedDashboardTechnicalRoute: AuthedDashboardTechnicalRoute,
  AuthedRemediationTasksRoute: AuthedRemediationTasksRoute,
  AuthedSoftwareIdRoute: AuthedSoftwareIdRoute,
  AuthedVulnerabilitiesIdRoute: AuthedVulnerabilitiesIdRoute,
  AuthedVulnerabilitiesChangesRoute: AuthedVulnerabilitiesChangesRoute,
  AuthedActionsIndexRoute: AuthedActionsIndexRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedApprovalsIndexRoute: AuthedApprovalsIndexRoute,
  AuthedAssetsIndexRoute: AuthedAssetsIndexRoute,
  AuthedAuditLogIndexRoute: AuthedAuditLogIndexRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDevicesIndexRoute: AuthedDevicesIndexRoute,
  AuthedRemediationIndexRoute: AuthedRemediationIndexRoute,
  AuthedSoftwareIndexRoute: AuthedSoftwareIndexRoute,
  AuthedVulnerabilitiesIndexRoute: AuthedVulnerabilitiesIndexRoute,
  AuthedAdminAssetRulesIdRoute: AuthedAdminAssetRulesIdRoute,
  AuthedAdminAssetRulesNewRoute: AuthedAdminAssetRulesNewRoute,
  AuthedAdminPlatformAiRoute: AuthedAdminPlatformAiRoute,
  AuthedAdminPlatformNotificationsRoute: AuthedAdminPlatformNotificationsRoute,
  AuthedAdminTeamsIdRoute: AuthedAdminTeamsIdRoute,
  AuthedAdminTenantsIdRoute: AuthedAdminTenantsIdRoute,
  AuthedAdminWorkflowsIdRoute: AuthedAdminWorkflowsIdRoute,
  AuthedAdminWorkflowsNewRoute: AuthedAdminWorkflowsNewRoute,
  AuthedAssetsIdRemediationRoute: AuthedAssetsIdRemediationRoute,
  AuthedRemediationTaskIdRoute: AuthedRemediationTaskIdRoute,
  AuthedSoftwareIdRemediationRoute: AuthedSoftwareIdRemediationRoute,
  AuthedAdminAssetRulesIndexRoute: AuthedAdminAssetRulesIndexRoute,
  AuthedAdminIntegrationsIndexRoute: AuthedAdminIntegrationsIndexRoute,
  AuthedAdminTeamsIndexRoute: AuthedAdminTeamsIndexRoute,
  AuthedAdminTenantsIndexRoute: AuthedAdminTenantsIndexRoute,
  AuthedAdminWorkflowsIndexRoute: AuthedAdminWorkflowsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiEventsRoute: ApiEventsRoute,
  ApiIngestionRunEventsRoute: ApiIngestionRunEventsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  SetupIndexRoute: SetupIndexRoute,
  ApiInternalEventsRoute: ApiInternalEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
